title: Capiamo i bambini
author: 'lrusso96'
# description: ''
lang: 'it'
# baseurl: ""
url: ""
assets_path: '/assets/'

collections:
  projects:

# Build settings
theme: jekyll-theme-startbootstrap-agency
# remote_theme: SotiriosVrachas/jekyll-theme-startbootstrap-agency
plugins:
  - jekyll-remote-theme
